pre_execute:
  cs_ratio:
    - "Low"
    - "Medium"
    - "High"
  use_tools: true
  topics:
    - "Tourism"
    - "Weather"
    - "Shopping"
    - "Food"
    - "Exam"
    - "Politics"
  tense:
    - "Past"
    - "Present"
    - "Future"
  perspective:
    - "First Person"
    - "Third Person"
  character_setting:
    nationality:
      first_language: "Cantonese"
      second_language: "English"
    age:
      - "8-17"
      - "18-25"
      - "26-35"
      - "56-65"
      - "66+"
    gender:
      - "Male"
      - "Female"
    education_level:
      - "High School"
      - "College"
      - "Master"
      - "Doctor"
  output_type:
    - "single_turn"
    - "multi-turn"
  output_format:
    "json"
    
  

on_execute:
  round: 1
  verbose: true


